global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 10s
rule_files:
  - 'prometheus.rules.yml'
scrape_configs:
- job_name: prometheus
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - localhost:9090
- job_name: 'example-random'
  # Override the global default and scrape targets from this job every 5 seconds.
  scrape_interval: 5s
  static_configs:
   - targets: ['192.168.178.79:8080', '192.168.178.79:8081']
     labels:
       group: 'production'

   - targets: ['192.168.178.79:8082']
     labels:
       group: 'canary'
